### PR TITLE
Update to 1.14.2

### PR DESCRIPTION
**Pull request by selfslaughter**
Basic update to support 1.14.2

Shaded in required parts of apache-commons as they are no longer included in spigot.

### CODE REVIEW

**Comment by selfslaughter** [comment]
Note: No support for 1.13

**Comment by wispoffates** [comment]
Wanted to let you know I'll be using this as a base to update to 1.14.3 but I'm not going to merge it directly.

1. Gitlab is the main development host and I'm not sure what merging this over here would transfer over.
2.  Since the 1.14 changes don't look that drastic I'm going to investigate if I can keep 1.13 and 1.14 compatibility together.  I only split 1.12 and 1.13 up because the changes were so drastic.

**Comment by selfslaughter** [comment]
No worries. Wasn't anything major in the change to 1.14 apart from the apache-commons stuff.

I didn't bother with 1.13 compatibility as it was originally only a quick test to get it running, but it's been running solid on our server for the last month or so anyway.

Only current issue I'm aware of is staff using the artkits in creative mode and moving the "back/forward page" items into their inventory. But given the amount of other problems 1.14 has with anything to do with chunk loading, its been low priority. ;)

**Comment by wispoffates** [comment]
Closing this now as 1.14 support is out.

**Pull request closed without merging**
